name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: WinFormsApp.sln
      Test_Project_Path: ..\Implementation.Tests\Implementation.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore the solution
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build all projects
      run: dotnet build ${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU"

    - name: Execute unit tests
      run: dotnet test ${{ env.Test_Project_Path }} /p:Configuration=${{ matrix.configuration }}

    - name: Create release package
      run: dotnet publish WinFormsApp/WinFormsApp.csproj --configuration ${{ matrix.configuration }} --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: |
          **/bin/${{ matrix.configuration }}/
          **/obj/${{ matrix.configuration }}/
          publish/
